# Generated by Django 4.2.2 on 2023-10-31 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Item name')),
                ('rating', models.FloatField(verbose_name='Item rating')),
                ('description', models.TextField(blank=True, max_length=8192, verbose_name='Item description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_last_modified', models.DateTimeField(auto_now=True, verbose_name='Date last modified')),
                ('from_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
